### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by netplayer** [vijayrami/kbmarketplace#1]
Which Prestashop version does it target? There was a db foreign key error while trying to install the module on version 1.6.17 .  Worked around it installing db tables manually but then there is another error with overrides obviously related to the db.

**Comment by netplayer** [comment]
Bought the paid version on the official site, all ok

**Comment by alielgarhi** [comment]
The following module(s) could not be installed properly:

    kbmarketplace :
        Error in installing overrides same methods may be already overridden , please try again after clearing cache or contact to support.

**Comment by netplayer** [comment]
> The following module(s) could not be installed properly:
> 
> ```
> kbmarketplace :
>     Error in installing overrides same methods may be already overridden , please try again after clearing cache or contact to support.
> ```
Well the error contains the solution, i say by own experience, you have to block installing overrides automatically and install them afterwards manually. But still the package has some functional problems. I had to buy the commercial version and didn't regret. Saved me a ton of time.

**Comment by firatpolat13** [comment]
Hello, I am getting this error .. "Cannot install module kbmarketplace. Override issue, please try again after clearing cache or contact to support." can you explain how to solve this issue. Thanks in advance
